# Generated by Django 4.2.5 on 2023-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_reception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periphery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='reception',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='scaner',
        ),
    ]
