# Generated by Django 4.2.5 on 2023-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_periphery_remove_reception_printer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='printer',
            field=models.ManyToManyField(to='branches.periphery'),
        ),
    ]
