# Generated by Django 4.2.5 on 2023-10-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.TextField(),
        ),
    ]
